Repository GraphicsReplicability/replicability.graphics, pull requests merged in 2020-04, with the labels that each got.

#2 [WIP] Disqus update
  scripts/generatePagesFromConsolidatedJSON.py
Labels: website-bug

#6 Altmetric with secret key
  .github/workflows/#preDeploy.yml#
  .github/workflows/checkJSON.yml
  .github/workflows/deploysite.yml
  .github/workflows/preDeploy.yml
  scripts/deployWeb.sh
  scripts/fetchData.py
  scripts/generatePagesFromConsolidatedJSON.py
Labels: website-improvement

#18 Adding tooltip text on badges
  scripts/generatePagesFromConsolidatedJSON.py
Labels: website-improvement

#16 Typo + wrong GitHub link
  scripts/generatePagesFromConsolidatedJSON.py
  template.json
Labels: website-bug, website-improvement

#17 Update HTML code for a better web indexing.
  scripts/generatePagesFromConsolidatedJSON.py
  website-source/header-snippet.html
Labels: website-improvement

#20 "The Team" section with logos
  scripts/generatePagesFromConsolidatedJSON.py
  website-source/footer-snippet.html
  website-source/images/logo_cnrs.png
  website-source/images/logo_irit.png
  website-source/images/logo_liris.png
Labels: website-improvement

#5 Refactor charts
  scripts/generatePagesFromConsolidatedJSON.py
  website-source/assets/js/browse-updateViz.js
  website-source/assets/js/mychart.js
  website-source/footer-snippet.html
Labels: website-improvement

#41 Add missing file sortArrays.js
  website-source/assets/js/sortArrays.js
Labels: website-bug

#55 Remove GS col
  scripts/generatePagesFromConsolidatedJSON.py
Labels: website-improvement

#60 Add new fields to data digest + fix html bugs
  scripts/generatePagesFromConsolidatedJSON.py
Labels: website-improvement
