Repository GraphicsReplicability/replicability.graphics, pull requests merged in 2020-05, with the labels that each got.

#83 GRSI text
  scripts/generatePagesFromConsolidatedJSON.py
Labels: website-improvement

#91 Update wrong entry
  data/siggraph-2014/10.1145-2601097.2601138.json
Labels: data-bug

#92 Add note about self-reviews
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  scripts/generatePagesFromConsolidatedJSON.py
Labels: documentation

#103 Fix misplaced div misc
  scripts/generatePagesFromConsolidatedJSON.py
Labels: website-bug

#108 10.1145-3306346.3323017
  data/siggraph-2019/10.1145-3306346.3323017.json
  scripts/checkJSONConsistency.py
Labels: new-review
